### ISSUE TITLE
Need

### ISSUE THREAD

**Issue by Bishopmarie** [apivideo/api.video-ios-client#35]

**Comment by Bishopmarie** [comment]
Need help

**Comment by olivierapivideo** [comment]
Hi @Bishopmarie,

Would it be possible to have a little more detail?

**Comment by Bishopmarie** [comment]
> Hi @Bishopmarie,
> 
> 
> 
> Would it be possible to have a little more detail? 

Good question- sorry for late reply- when they say just got to GitHub unsure how to get the program to actually transpire into an actual application 

The official iOS client library for api.video 

I'd like to add books to library site 😊

**Comment by olivierapivideo** [comment]
Closing since that seems not related to this repo.
